version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_cafe_tests
    user: root
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file:
      - n8n.env
    volumes:
      - n8n_data:/home/node/.n8n
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/docker:/usr/bin/docker

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok_cafe_tunnel
    restart: unless-stopped
    command:
      - "http"
      - "n8n:5678"
    env_file:
      - n8n.env
    ports:
      - "4040:4040"
    depends_on:
      - n8n

volumes:
  n8n_data:
    driver: local
